source_directories:
  - /home/sysadmin/srv-docker/gitea

repositories:
  - path: /mnt/windows-backup
    label: windows-backup
    encryption: none

compression: lzma
archive_name_format: '{hostname}-{now}'

keep_daily: 3
keep_weekly: 2
keep_monthly: 3

verbosity: 1

# postgresql_databases:
#   - name: all
#     hostname: srv-prod-2.nfg-tech.com
#     port: 5432
#     username: admin
#     password:
#     pg_dump_command: docker exec postgresdb pg_dumpall
#     pg_restore_command: docker exec postgresdb pg_restore

commands:
  - before: action
    when: [create]
    run:
      - echo "Before create!"
      # - /usr/local/bin/mount-borg-smb.sh
  - after: action
    when:
      - create
      - prune
    run:
      # - /usr/local/bin/unmount-borg-smb.sh
      - echo "After create or prune!"
  - after: error
    run:
      # - /usr/local/bin/unmount-borg-smb.sh
      - echo "Something went wrong!"
