# ArchRiot User Keybindings
# -----------------------------------------------------------------------------
# This file is sourced by your main Hyprland config:
#   ~/.config/hypr/hyprland.conf
#
# Purpose:
# - Keep your personal keybindings separate from the base config
# - Keep your personal application preferences separate from the base config
# - Persist across installs/repairs (the installer preserves this file)
#
# Usage:
# - Add your custom `bind` lines below
# - `unbind` keys that overlap with defaults
# - Add inline # Description to appear on keymap panel.($mod SHIFT H)
# - Change or add application variables for launchers
# - Reload Hyprland to apply changes:
#     hyprctl reload
#
# Notes:
# - $mod and apps ($terminal etc) are defined in the main config (usually SUPER)
# - If a bind here conflicts with a base bind, you need to `unbind` them first.
# - Inline comments will be used as key description on help panel (e.g.: $mod, x, exec, twitter  # Twitter App)
# - Keybindings without inline # Description will not show up on the keymap panel.
# - Prefer consistency and minimal overlap with system defaults.
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Add / Overwrite applications (Examples)
# -----------------------------------------------------------------------------

# $mod = WINKEY                            # Use a different bind for MOD key
$terminal = ghostty
$fileManager = Thunar
$browser = archriot-brave

# -----------------------------------------------------------------------------
# Unified Fullscreen (Examples)
# -----------------------------------------------------------------------------

bind = $mod, F11, fullscreen

# -----------------------------------------------------------------------------
# Custom Keybindings
# -----------------------------------------------------------------------------

# Resets
unbind = $mod, O
unbind = $mod, Z
unbind = $mod, G
unbind = $mod, S
unbind = $mod, R
unbind = $mod, N
unbind = $mod, X
unbind = $mod, M
unbind = $mod, E
unbind = $mod, F
unbind = $mod, V
unbind = $mod, space
unbind = $mod SHIFT, X
unbind = $mod CTRL, SPACE

# Window Management
bind = $mod, space, togglefloating, # Toggle Floating

# Bindings
bind = CTRL, slash, exec, fuzzel # App Launcher
